# Build steps need access to the Docker agent
sudo: required
services:
  - docker

jobs:
  include:

    # Run all the tests inside Docker

    - stage: Test
      script: docker build -f Dockerfile.test .


    # If this is a tagged commit, publish the package to npm

    - stage: Release npm
      script: echo "Deploying to npm"
      deploy:
        provider: npm
        email: asyncadventures@gmail.com
        api_key: $NPM_TOKEN
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+

    # If this is a tagged commit, publish a new Docker image

    - stage: Release Docker
      script: echo "Deploying to DockerHub"
      deploy:
        provider: script
        script: scripts/travis-release-docker
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
